# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Funny comment
        uses: Marta83/funny-comment-action@v2.1
        with:
          # Github Token for authentication
          GITHUB_TOKEN: ${{ secrets.TOKEN}}
          # GIPHY Token to use in your funny comments, remember you can use github secrets
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN}}
          # You can choose between chuck, to get random Chuck Norries facts,  gif, to get random gifs, or all, to get a random message
          comment_type: 'gif'
